name: assignment3
on: 
  push:
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the image
        run: |
          docker build . --file Dockerfile --tag myapp:latest
          docker save myapp:latest -o myapp.tar
      - name: updating the log file, if succesful image built
        if: success()
        run: |
          current_time=$(TZ=Asia/Jerusalem date -Iminutes)
          echo " $current_time" > log.txt
          echo "Sagi Vaknin and Rani Bezalel" >> log.txt
          echo "image successfully built" >> log.txt 
      - name: updating the log file, if failure in image build
        if: failure()
        run: |
          current_time=$(TZ=Asia/Jerusalem date -Iminutes)
          echo " $current_time" > log.txt
          echo "Sagi Vaknin and Rani Bezalel" >> log.txt
          echo "image not able to be built" >> log.txt 
      - name: upload the image
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: myapp.tar
      - name: upload the log file into GitHub repo
        if: always()
        uses: actions/upload-artifact@v3
        with: 
          name: logfile
          path: log.txt

    test:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest 
          pip install requests
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: Load docker image
        run: docker load --input myimage/myapp.tar
      - name: check myimage image is loaded
        run: docker image ls
      - name: run image in container
        run: docker run -p 8000:8000 myapp:latest &
      - name: update the log file if the container is running
        if: success()
        run: |
          cd logfile
          echo "Container up and running" >> log.txt
      - name: update the log file if the container is not running properly
        if: failure()
        run: |
          cd logfile
          echo "Container failed to run" >> log.txt
      - name: run pytest tests
        run: |
          cd tests
          pytest -v assn3_tests.py > assn3_test_results.txt
      - name: update the log file with successful test results
        if: success()
        run: |
          cd logfile
          echo "tests succeeded" >> log.txt
      - name: update the log file with failed test results
        if: failure()
        run: |
          cd logfile
          echo "tests failed" >> log.txt
      - name: upload the updated log file
        if: always()
        uses: actions/upload-artifact@v3
        with: 
          name: logfile
          path: logfile/log.txt   
      - name: upload the test results
        if: always() 
        uses: actions/upload-artifact@v3
        with:
          name: GH_test_results
          path: tests/assn3_test_results.txt
  
    query:
      needs: test
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: Load docker image
        run: docker load --input myimage/myapp.tar
      - name: check myimage image is loaded
        run: docker image ls
      - name: run image in container
        run: docker run -p 8000:8000 myapp:latest &
      - name: run a python script to execute queries from query.txt
        run: |
          python3 query_runner.py
      - name: upload response.txt
        uses: actions/upload-artifact@v3
        with:
          name: response
          path: response.txt

